pipeline {
    agent any

    stages {

        stage('Compile') {
            steps {
                sh '''#!/bin/bash
                	echo "Compiling code..."
                	./sbt compile
                	echo "Done compiling"
         		'''
            }
        }

        stage('Test') {
            steps {
                sh '''#!/bin/bash
                    echo "Checking docker"
                    drpsa
                    echo "Finished checking docker"
                    echo "Running all tests..."
                    ./sbt test
                    if [ $? -ne 0 ] ; then
                      echo "One or more tests failed, marking this build as a failure."
                      exit 1
                    fi
                    echo "Test run complete."
                '''
            }
        }
    }
}